#!/usr/bin/env python
# -*- coding: utf-8 -*-

from google.appengine.ext import db
import datetime

import datastores

matomesites = (('http://blog.livedoor.jp/dqnplus/',u'痛いニュース'),
                         ('http://news4vip.livedoor.biz/',u'ニュー速クオリティ'),
                         ('http://hamusoku.com/',u'ハムスター速報'),
                         ('http://guideline.livedoor.biz/',u'日刊スレッドガイド'),
                         ('http://alfalfalfa.com/',u'アルファルファモザイク'),
                         ('http://kanasoku.blog82.fc2.com/',u'カナ速'),
                         ('http://waranote.blog76.fc2.com/',u'ワラノート'),
                         ('http://blog.livedoor.jp/news23vip/',u'VIPPERな俺'),
                         ('http://www.kajisoku.org/',u'カジ速'),
                         ('http://imihu.blog30.fc2.com/',u'イミフｗｗうはｗｗｗおｋｗｗｗ'),
                         ('http://blog.livedoor.jp/michaelsan/',u'もみあげチャ～シュ～'),
                         ('http://slpy.blog65.fc2.com/',u'SLPY'),
                         ('http://news4wide.livedoor.biz/',u'VIPワイドガイド'),
                         ('http://newsteam.livedoor.biz/',u'スチーム速報　ＶＩＰ'),
                         ('http://workingnews.blog117.fc2.com/',u'人生VIP職人ブログwww'),
                         ('http://blog.livedoor.jp/goldennews/',u'ゴールデンタイムズ'),
                         ('http://ksklog.blog108.fc2.com/',u'かそログ'),
                         ('http://hebiya.blog40.fc2.com/',u'面白蛇屋'),
                         ('http://notorious2.blog121.fc2.com/',u'のとーりあす'),
                         ('http://nantara.seesaa.net/',u'なんたらかんたら'),
                         ('http://mootoko.blog.shinobi.jp/',u'喪男のまとめ切れない事。'),
                         ('http://chasoku.blog.shinobi.jp/',u'茶速'),
                         ('http://blog.livedoor.jp/wordroom/',u'イフカルト'),
                         ('http://blog.livedoor.jp/insidears/',u'【2ch】ニュー速VIPブログ(`･ω･´)'),
                         ('http://blog.livedoor.jp/kaibu222/',u'カゼタカ2ブログch'),
                         ('http://mudainodqnment.blog35.fc2.com/',u'無題のドキュメント'),
                         ('http://kaisun1192.blog121.fc2.com/',u'おはようｗｗお前らｗｗｗｗ'),
                         ('http://afoafodayo.blog84.fc2.com/',u'アフォBlog'),
                         ('http://ibra.blog52.fc2.com/',u'厳選１スレ'),
                         ('http://blog.livedoor.jp/himasoku123/',u'暇人＼(＾o＾)／速報'),
                         ('http://anchor18.blog77.fc2.com/',u'あんか～びっぷ'),
                         ('http://nicovip2ch.blog44.fc2.com/',u'ニコニコVIP2ch'),
                         ('http://gasoku.livedoor.biz/',u'ヴィブロ'),
                         ('http://limitedxlimited.blog22.fc2.com/',u'LLR'),
                         ('http://punpunpun.blog107.fc2.com/',u'ぷん太のにゅーす'),
                         ('http://yaruomatome.blog10.fc2.com/',u'やる夫ブログ'),
                         ('http://mukankei961.blog105.fc2.com/',u'やる夫短編集　地獄編'),
                         ('http://blog.livedoor.jp/kusovip/',u'クソスレドンキーノ'),
                         ('http://inusoku.blog87.fc2.com/',u'犬速VIP@わんわんおｗｗｗ'),
                         ('http://tamasoku.blog35.fc2.com/',u'たま速報'),
                         ('http://blog.livedoor.jp/ringotomomin/',u'V速ニュップ'),
                         ('http://suiseisekisuisui.blog107.fc2.com/',u'すくいぬ'),
                         ('http://alsoku.blog47.fc2.com/',u'アルカン速報'),
                         ('http://burusoku-vip.com/',u'ぶる速-VIP'),
                         ('http://namaekurekure.blog116.fc2.com/',u'名前を付けて保存する。'),
                         ('http://konogoro2ch.blog117.fc2.com/',u'このごろ２ちゃんねる'),
                         ('http://ptaroi.blog46.fc2.com/',u'vip報知ねむいよ！(・∀・)'),
                         ('http://digital-thread.com/',u'デジタルニューススレッド'),
                         ('http://404nots.blog88.fc2.com/',u'ニュース速報BIP'),
                         ('http://tannsokuvip.blog54.fc2.com/',u'たん速'),
                         ('http://shibasoku.livedoor.biz/',u'柴犬速報'),
                         ('http://medetashimedetashi03.blog17.fc2.com/',u'めでたしめでたし'),
                         ('http://blog.livedoor.jp/minnanohimatubushi/',u'みんなの(=ﾟωﾟ)人(ﾟωﾟ=)暇つぶし'),
                         ('http://blog.livedoor.jp/booq/',u'まとめたニュース'),
                         ('http://newslog2ch.blog8.fc2.com/',u'秒速ニューろぐ'),
                         ('http://news020.blog13.fc2.com/',u'ニュース２ちゃんねる'),
                         ('http://revchannel.blog64.fc2.com/',u'特設ニュースちゃんねる'),
                         ('http://blog.livedoor.jp/a6news/',u'A6ニュース（ﾟДﾟ）'),
                         ('http://freefairy.blog84.fc2.com/',u'心ニュース'),
                         ('http://teranews.livedoor.biz/',u'テラニュース'),
                         ('http://yutori2ch.blog67.fc2.com/',u'(´A｀)＜咳をしてもゆとり'),
                         ('http://newtou.info/',u'ニュー投'),
                         ('http://warasoku.blog18.fc2.com/',u'ワラ速'),
                         ('http://watch2ch.2chblog.jp/',u'watch@2チャンネル'),
                         ('http://giraffech.blog.shinobi.jp/',u'キリンちゃんねる'),
                         ('http://blog.livedoor.jp/jyoushiki43/',u'常識的に考えた'),
                         ('http://horo346.blog75.fc2.com/',u'にゅーるぽ（・∀・）'),
                         ('http://nw2.blog112.fc2.com/',u'ﾆｭｰｽｳｫｯﾁ２ちゃんねる'),
                         ('http://aresoku.blog42.fc2.com/',u'ちょっとアレなニュース'),
                         ('http://milfled.seesaa.net/',u'何でもありんす'),
                         ('http://blog.livedoor.jp/video_news/',u'東京エスノ'),
                         ('http://2chcopipe.com/',u'2chコピペ保存道場'),
                         ('http://www.res2ch.net/',u'２ちゃんねる実況中継'),
                         ('http://ayacnews2nd.com/',u'ぁゃιぃ(*ﾟーﾟ)NEWS 2nd'),
                         ('http://mousouteki.blog53.fc2.com/',u'続・妄想的日常'),
                         ('http://blog.livedoor.jp/deal_with0603/',u'ムズ痒いブログ'),
                         ('http://copipe.info/',u'コピペ新聞'),
                         ('http://phlogiston.blog110.fc2.com/',u'引いた瞬間、冷めた瞬間'),
                         ('http://ikuzi2.blog73.fc2.com/',u'育児板拾い読み＠２ｃｈ'),
                         ('http://mogeonna.seesaa.net/',u'喪ゲ女'),
                         ('http://tenkomo.blog46.fc2.com/',u'てんこもり。'),
                         ('http://copypa.blog99.fc2.com/',u'コピペ馬鹿'),
                         ('http://honwaka2ch.blog90.fc2.com/',u'ほんわか2ちゃんねる'),
                         ('http://aa2ki.blog108.fc2.com/',u'AAなにっき....〆ﾐ・д・,,'),
                         ('http://nikuch.blog42.fc2.com/',u'にくろぐ。'),
                         ('http://blog.livedoor.jp/domesaka/',u'芸スポまとめblog'),
                         ('http://yunakiti.blog79.fc2.com/',u'今日もやられやく'),
                         ('http://vipper2ch.blog94.fc2.com/',u'ゲー速＠2ch'),
                         ('http://miruyo.blog38.fc2.com/',u'ゲーム板見るよ！'),
                         ('http://vipvipblogblog.blog119.fc2.com/',u'ベア速'))
for matomesite in matomesites:
  query = datastores.Sites.gql('WHERE url = :url',url=matomesite[0])
  site = query.get()
  if not site:
    site = datastores.Sites()
    site.url = matomesite[0]
    site.title = matomesite[1]
    site.check_time = datetime.datetime.today()
    site.put()